name: "Check PR Source Branch For Release Branch"

# Rule only enforced on PRs to release branches.
on:
  pull_request:
    branches:
      - release/*

jobs:
  check-branch:
    name: Check PR Source Branch For Release Branch
    runs-on: ubuntu-latest
    env:
      ALLOWED_PREFIXES: "feature/ bugfix/ chore/"
    steps:
      - name: Check source branch name
        run: |
          echo "Source branch: ${{ github.head_ref }}"
          
          matched=false
          for prefix in $ALLOWED_PREFIXES; do
            if [[ "${{ github.head_ref }}" == "$prefix"* ]]; then
              matched=true
              break
            fi
          done

          if [ "$matched" = false ]; then
            echo "❌ Error: Source branch must start with one of: $ALLOWED_PREFIXES"
            exit 1
          else
            echo "✅ Source branch prefix is valid."
          fi
